server:
  port: 8080

# Gateway routing rules
spring:
  cloud:
    gateway:      
      server:
        webflux:
          forwarded:
            enabled: true
          x-forwarded:
            enabled: true
            proto-enabled: true
            host-enabled: true
            port-enabled: true
          globalcors:
            cors-configurations:
              '[/**]': 
                allowedOrigins: "http://localhost:3000" 
                allowedMethods:
                  - GET
                  - POST
                allowedHeaders: "*"
          default-filters:
            - PreserveHostHeader
                  
          routes:
            - id: discovery-server-route
              uri: lb://discovery-server
              predicates:
                - Path=/eureka/**
            - id: test-service-route
              uri: lb://test-service
              predicates:
                - Path=/test/**
              filters:
                - RewritePath=/test/(?<segment>.*), /$\{segment}
            - id: auth-server-login-route
                uri: lb://auth-server
                predicates:
                  - Path=/.well-known/**,/oauth2/**,/login,/logout,/consent
                preserveHostHeader: true 