server:
  port: 8080

# Eureka client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

# Gateway routing rules
spring:
  cloud:
    gateway:      
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]': 
                allowedOrigins: "http://localhost:3000" 
                allowedMethods:
                  - GET
                  - POST
                allowedHeaders: "*"
          routes:
            - id: discovery-server-route
              uri: lb://discovery-server
              predicates:
                - Path=/eureka/**
            - id: auth-server-login-route
              uri: lb://auth-server
              predicates:
                - Path=/login/**
            # This line is now correctly indented
            - id: auth-server-oauth-route
              uri: lb://auth-server
              predicates:
                - Path=/oauth2/**
            - id: test-service-route
              uri: lb://test-service
              predicates:
                - Path=/test/**
              filters:
                - RewritePath=/test/(?<segment>.*), /$\{segment}
            - id: auth-server-oidc-route
              uri: lb://auth-server
              predicates:
                - Path=/.well-known/**