# --- Default Profile Properties ---
app:
  auth:
    issuer-uri: http://localhost:8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    org.springframework.security: TRACE
    com.trading: TRACE

# ---Prod Profile Properties ---
---

spring:
  config:
    activate:
      on-profile: prod

app:
  auth:
    issuer-uri: https://api.your-domain.com

logging:
  level:
    org.springframework.security: INFO # Override to INFO for prod
    com.trading: INFO